// Code generated by protoc-gen-gogo.
// source: pb/counselor.proto
// DO NOT EDIT!

/*
	Package pb is a generated protocol buffer package.

	It is generated from these files:
		pb/counselor.proto

	It has these top-level messages:
		CheckActionReqResp
		DestinationConfig
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckActionReqResp struct {
	Name               string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command            []string                      `protobuf:"bytes,2,rep,name=command" json:"command,omitempty"`
	Args               []string                      `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
	Env                []string                      `protobuf:"bytes,4,rep,name=env" json:"env,omitempty"`
	Conf               map[string]string             `protobuf:"bytes,5,rep,name=conf" json:"conf,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	WorkDir            string                        `protobuf:"bytes,6,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Periodic           int32                         `protobuf:"varint,7,opt,name=periodic,proto3" json:"periodic,omitempty"`
	StateCode          string                        `protobuf:"bytes,8,opt,name=state_code,json=stateCode,proto3" json:"state_code,omitempty"`
	StateMessage       string                        `protobuf:"bytes,9,opt,name=state_message,json=stateMessage,proto3" json:"state_message,omitempty"`
	Timestamp          string                        `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DestinationPath    string                        `protobuf:"bytes,11,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	Selector           string                        `protobuf:"bytes,12,opt,name=selector,proto3" json:"selector,omitempty"`
	DestConfigurations map[string]*DestinationConfig `protobuf:"bytes,13,rep,name=dest_configurations,json=destConfigurations" json:"dest_configurations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CheckActionReqResp) Reset()                    { *m = CheckActionReqResp{} }
func (m *CheckActionReqResp) String() string            { return proto.CompactTextString(m) }
func (*CheckActionReqResp) ProtoMessage()               {}
func (*CheckActionReqResp) Descriptor() ([]byte, []int) { return fileDescriptorCounselor, []int{0} }

func (m *CheckActionReqResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckActionReqResp) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *CheckActionReqResp) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *CheckActionReqResp) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *CheckActionReqResp) GetConf() map[string]string {
	if m != nil {
		return m.Conf
	}
	return nil
}

func (m *CheckActionReqResp) GetWorkDir() string {
	if m != nil {
		return m.WorkDir
	}
	return ""
}

func (m *CheckActionReqResp) GetPeriodic() int32 {
	if m != nil {
		return m.Periodic
	}
	return 0
}

func (m *CheckActionReqResp) GetStateCode() string {
	if m != nil {
		return m.StateCode
	}
	return ""
}

func (m *CheckActionReqResp) GetStateMessage() string {
	if m != nil {
		return m.StateMessage
	}
	return ""
}

func (m *CheckActionReqResp) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *CheckActionReqResp) GetDestinationPath() string {
	if m != nil {
		return m.DestinationPath
	}
	return ""
}

func (m *CheckActionReqResp) GetSelector() string {
	if m != nil {
		return m.Selector
	}
	return ""
}

func (m *CheckActionReqResp) GetDestConfigurations() map[string]*DestinationConfig {
	if m != nil {
		return m.DestConfigurations
	}
	return nil
}

type DestinationConfig struct {
	Name            string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command         []string          `protobuf:"bytes,2,rep,name=command" json:"command,omitempty"`
	Args            []string          `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
	Env             []string          `protobuf:"bytes,4,rep,name=env" json:"env,omitempty"`
	Conf            map[string]string `protobuf:"bytes,5,rep,name=conf" json:"conf,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	WorkDir         string            `protobuf:"bytes,6,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Periodic        int32             `protobuf:"varint,7,opt,name=periodic,proto3" json:"periodic,omitempty"`
	StateCode       string            `protobuf:"bytes,8,opt,name=state_code,json=stateCode,proto3" json:"state_code,omitempty"`
	StateMessage    string            `protobuf:"bytes,9,opt,name=state_message,json=stateMessage,proto3" json:"state_message,omitempty"`
	Timestamp       string            `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DestinationPath string            `protobuf:"bytes,11,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
}

func (m *DestinationConfig) Reset()                    { *m = DestinationConfig{} }
func (m *DestinationConfig) String() string            { return proto.CompactTextString(m) }
func (*DestinationConfig) ProtoMessage()               {}
func (*DestinationConfig) Descriptor() ([]byte, []int) { return fileDescriptorCounselor, []int{1} }

func (m *DestinationConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DestinationConfig) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *DestinationConfig) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *DestinationConfig) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *DestinationConfig) GetConf() map[string]string {
	if m != nil {
		return m.Conf
	}
	return nil
}

func (m *DestinationConfig) GetWorkDir() string {
	if m != nil {
		return m.WorkDir
	}
	return ""
}

func (m *DestinationConfig) GetPeriodic() int32 {
	if m != nil {
		return m.Periodic
	}
	return 0
}

func (m *DestinationConfig) GetStateCode() string {
	if m != nil {
		return m.StateCode
	}
	return ""
}

func (m *DestinationConfig) GetStateMessage() string {
	if m != nil {
		return m.StateMessage
	}
	return ""
}

func (m *DestinationConfig) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *DestinationConfig) GetDestinationPath() string {
	if m != nil {
		return m.DestinationPath
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckActionReqResp)(nil), "pb.CheckActionReqResp")
	proto.RegisterType((*DestinationConfig)(nil), "pb.DestinationConfig")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CounselorService service

type CounselorServiceClient interface {
	CreateCheck(ctx context.Context, in *CheckActionReqResp, opts ...grpc.CallOption) (*CheckActionReqResp, error)
	ReapCheck(ctx context.Context, in *CheckActionReqResp, opts ...grpc.CallOption) (*CheckActionReqResp, error)
	UpdateCheck(ctx context.Context, in *CheckActionReqResp, opts ...grpc.CallOption) (*CheckActionReqResp, error)
	DeleteCheck(ctx context.Context, in *CheckActionReqResp, opts ...grpc.CallOption) (*CheckActionReqResp, error)
}

type counselorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCounselorServiceClient(cc *grpc.ClientConn) CounselorServiceClient {
	return &counselorServiceClient{cc}
}

func (c *counselorServiceClient) CreateCheck(ctx context.Context, in *CheckActionReqResp, opts ...grpc.CallOption) (*CheckActionReqResp, error) {
	out := new(CheckActionReqResp)
	err := grpc.Invoke(ctx, "/pb.CounselorService/CreateCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counselorServiceClient) ReapCheck(ctx context.Context, in *CheckActionReqResp, opts ...grpc.CallOption) (*CheckActionReqResp, error) {
	out := new(CheckActionReqResp)
	err := grpc.Invoke(ctx, "/pb.CounselorService/ReapCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counselorServiceClient) UpdateCheck(ctx context.Context, in *CheckActionReqResp, opts ...grpc.CallOption) (*CheckActionReqResp, error) {
	out := new(CheckActionReqResp)
	err := grpc.Invoke(ctx, "/pb.CounselorService/UpdateCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counselorServiceClient) DeleteCheck(ctx context.Context, in *CheckActionReqResp, opts ...grpc.CallOption) (*CheckActionReqResp, error) {
	out := new(CheckActionReqResp)
	err := grpc.Invoke(ctx, "/pb.CounselorService/DeleteCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CounselorService service

type CounselorServiceServer interface {
	CreateCheck(context.Context, *CheckActionReqResp) (*CheckActionReqResp, error)
	ReapCheck(context.Context, *CheckActionReqResp) (*CheckActionReqResp, error)
	UpdateCheck(context.Context, *CheckActionReqResp) (*CheckActionReqResp, error)
	DeleteCheck(context.Context, *CheckActionReqResp) (*CheckActionReqResp, error)
}

func RegisterCounselorServiceServer(s *grpc.Server, srv CounselorServiceServer) {
	s.RegisterService(&_CounselorService_serviceDesc, srv)
}

func _CounselorService_CreateCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckActionReqResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounselorServiceServer).CreateCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CounselorService/CreateCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounselorServiceServer).CreateCheck(ctx, req.(*CheckActionReqResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _CounselorService_ReapCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckActionReqResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounselorServiceServer).ReapCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CounselorService/ReapCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounselorServiceServer).ReapCheck(ctx, req.(*CheckActionReqResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _CounselorService_UpdateCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckActionReqResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounselorServiceServer).UpdateCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CounselorService/UpdateCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounselorServiceServer).UpdateCheck(ctx, req.(*CheckActionReqResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _CounselorService_DeleteCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckActionReqResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounselorServiceServer).DeleteCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CounselorService/DeleteCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounselorServiceServer).DeleteCheck(ctx, req.(*CheckActionReqResp))
	}
	return interceptor(ctx, in, info, handler)
}

var _CounselorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CounselorService",
	HandlerType: (*CounselorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCheck",
			Handler:    _CounselorService_CreateCheck_Handler,
		},
		{
			MethodName: "ReapCheck",
			Handler:    _CounselorService_ReapCheck_Handler,
		},
		{
			MethodName: "UpdateCheck",
			Handler:    _CounselorService_UpdateCheck_Handler,
		},
		{
			MethodName: "DeleteCheck",
			Handler:    _CounselorService_DeleteCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/counselor.proto",
}

func (m *CheckActionReqResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CheckActionReqResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Command) > 0 {
		for _, s := range m.Command {
			dAtA[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.Args) > 0 {
		for _, s := range m.Args {
			dAtA[i] = 0x1a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.Env) > 0 {
		for _, s := range m.Env {
			dAtA[i] = 0x22
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.Conf) > 0 {
		for k, _ := range m.Conf {
			dAtA[i] = 0x2a
			i++
			v := m.Conf[k]
			mapSize := 1 + len(k) + sovCounselor(uint64(len(k))) + 1 + len(v) + sovCounselor(uint64(len(v)))
			i = encodeVarintCounselor(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintCounselor(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintCounselor(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if len(m.WorkDir) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(len(m.WorkDir)))
		i += copy(dAtA[i:], m.WorkDir)
	}
	if m.Periodic != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(m.Periodic))
	}
	if len(m.StateCode) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(len(m.StateCode)))
		i += copy(dAtA[i:], m.StateCode)
	}
	if len(m.StateMessage) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(len(m.StateMessage)))
		i += copy(dAtA[i:], m.StateMessage)
	}
	if len(m.Timestamp) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(len(m.Timestamp)))
		i += copy(dAtA[i:], m.Timestamp)
	}
	if len(m.DestinationPath) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(len(m.DestinationPath)))
		i += copy(dAtA[i:], m.DestinationPath)
	}
	if len(m.Selector) > 0 {
		dAtA[i] = 0x62
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(len(m.Selector)))
		i += copy(dAtA[i:], m.Selector)
	}
	if len(m.DestConfigurations) > 0 {
		for k, _ := range m.DestConfigurations {
			dAtA[i] = 0x6a
			i++
			v := m.DestConfigurations[k]
			msgSize := 0
			if v != nil {
				msgSize = v.Size()
				msgSize += 1 + sovCounselor(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovCounselor(uint64(len(k))) + msgSize
			i = encodeVarintCounselor(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintCounselor(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if v != nil {
				dAtA[i] = 0x12
				i++
				i = encodeVarintCounselor(dAtA, i, uint64(v.Size()))
				n1, err := v.MarshalTo(dAtA[i:])
				if err != nil {
					return 0, err
				}
				i += n1
			}
		}
	}
	return i, nil
}

func (m *DestinationConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DestinationConfig) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Command) > 0 {
		for _, s := range m.Command {
			dAtA[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.Args) > 0 {
		for _, s := range m.Args {
			dAtA[i] = 0x1a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.Env) > 0 {
		for _, s := range m.Env {
			dAtA[i] = 0x22
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.Conf) > 0 {
		for k, _ := range m.Conf {
			dAtA[i] = 0x2a
			i++
			v := m.Conf[k]
			mapSize := 1 + len(k) + sovCounselor(uint64(len(k))) + 1 + len(v) + sovCounselor(uint64(len(v)))
			i = encodeVarintCounselor(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintCounselor(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintCounselor(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if len(m.WorkDir) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(len(m.WorkDir)))
		i += copy(dAtA[i:], m.WorkDir)
	}
	if m.Periodic != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(m.Periodic))
	}
	if len(m.StateCode) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(len(m.StateCode)))
		i += copy(dAtA[i:], m.StateCode)
	}
	if len(m.StateMessage) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(len(m.StateMessage)))
		i += copy(dAtA[i:], m.StateMessage)
	}
	if len(m.Timestamp) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(len(m.Timestamp)))
		i += copy(dAtA[i:], m.Timestamp)
	}
	if len(m.DestinationPath) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintCounselor(dAtA, i, uint64(len(m.DestinationPath)))
		i += copy(dAtA[i:], m.DestinationPath)
	}
	return i, nil
}

func encodeFixed64Counselor(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Counselor(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintCounselor(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CheckActionReqResp) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCounselor(uint64(l))
	}
	if len(m.Command) > 0 {
		for _, s := range m.Command {
			l = len(s)
			n += 1 + l + sovCounselor(uint64(l))
		}
	}
	if len(m.Args) > 0 {
		for _, s := range m.Args {
			l = len(s)
			n += 1 + l + sovCounselor(uint64(l))
		}
	}
	if len(m.Env) > 0 {
		for _, s := range m.Env {
			l = len(s)
			n += 1 + l + sovCounselor(uint64(l))
		}
	}
	if len(m.Conf) > 0 {
		for k, v := range m.Conf {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovCounselor(uint64(len(k))) + 1 + len(v) + sovCounselor(uint64(len(v)))
			n += mapEntrySize + 1 + sovCounselor(uint64(mapEntrySize))
		}
	}
	l = len(m.WorkDir)
	if l > 0 {
		n += 1 + l + sovCounselor(uint64(l))
	}
	if m.Periodic != 0 {
		n += 1 + sovCounselor(uint64(m.Periodic))
	}
	l = len(m.StateCode)
	if l > 0 {
		n += 1 + l + sovCounselor(uint64(l))
	}
	l = len(m.StateMessage)
	if l > 0 {
		n += 1 + l + sovCounselor(uint64(l))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 1 + l + sovCounselor(uint64(l))
	}
	l = len(m.DestinationPath)
	if l > 0 {
		n += 1 + l + sovCounselor(uint64(l))
	}
	l = len(m.Selector)
	if l > 0 {
		n += 1 + l + sovCounselor(uint64(l))
	}
	if len(m.DestConfigurations) > 0 {
		for k, v := range m.DestConfigurations {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovCounselor(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovCounselor(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovCounselor(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *DestinationConfig) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCounselor(uint64(l))
	}
	if len(m.Command) > 0 {
		for _, s := range m.Command {
			l = len(s)
			n += 1 + l + sovCounselor(uint64(l))
		}
	}
	if len(m.Args) > 0 {
		for _, s := range m.Args {
			l = len(s)
			n += 1 + l + sovCounselor(uint64(l))
		}
	}
	if len(m.Env) > 0 {
		for _, s := range m.Env {
			l = len(s)
			n += 1 + l + sovCounselor(uint64(l))
		}
	}
	if len(m.Conf) > 0 {
		for k, v := range m.Conf {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovCounselor(uint64(len(k))) + 1 + len(v) + sovCounselor(uint64(len(v)))
			n += mapEntrySize + 1 + sovCounselor(uint64(mapEntrySize))
		}
	}
	l = len(m.WorkDir)
	if l > 0 {
		n += 1 + l + sovCounselor(uint64(l))
	}
	if m.Periodic != 0 {
		n += 1 + sovCounselor(uint64(m.Periodic))
	}
	l = len(m.StateCode)
	if l > 0 {
		n += 1 + l + sovCounselor(uint64(l))
	}
	l = len(m.StateMessage)
	if l > 0 {
		n += 1 + l + sovCounselor(uint64(l))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 1 + l + sovCounselor(uint64(l))
	}
	l = len(m.DestinationPath)
	if l > 0 {
		n += 1 + l + sovCounselor(uint64(l))
	}
	return n
}

func sovCounselor(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozCounselor(x uint64) (n int) {
	return sovCounselor(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CheckActionReqResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCounselor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CheckActionReqResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CheckActionReqResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Command", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Command = append(m.Command, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = append(m.Args, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Env", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Env = append(m.Env, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Conf", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var keykey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				keykey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapkey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLenmapkey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapkey := int(stringLenmapkey)
			if intStringLenmapkey < 0 {
				return ErrInvalidLengthCounselor
			}
			postStringIndexmapkey := iNdEx + intStringLenmapkey
			if postStringIndexmapkey > l {
				return io.ErrUnexpectedEOF
			}
			mapkey := string(dAtA[iNdEx:postStringIndexmapkey])
			iNdEx = postStringIndexmapkey
			if m.Conf == nil {
				m.Conf = make(map[string]string)
			}
			if iNdEx < postIndex {
				var valuekey uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCounselor
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					valuekey |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				var stringLenmapvalue uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCounselor
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLenmapvalue |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLenmapvalue := int(stringLenmapvalue)
				if intStringLenmapvalue < 0 {
					return ErrInvalidLengthCounselor
				}
				postStringIndexmapvalue := iNdEx + intStringLenmapvalue
				if postStringIndexmapvalue > l {
					return io.ErrUnexpectedEOF
				}
				mapvalue := string(dAtA[iNdEx:postStringIndexmapvalue])
				iNdEx = postStringIndexmapvalue
				m.Conf[mapkey] = mapvalue
			} else {
				var mapvalue string
				m.Conf[mapkey] = mapvalue
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkDir", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkDir = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Periodic", wireType)
			}
			m.Periodic = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Periodic |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Selector", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Selector = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestConfigurations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var keykey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				keykey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapkey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLenmapkey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapkey := int(stringLenmapkey)
			if intStringLenmapkey < 0 {
				return ErrInvalidLengthCounselor
			}
			postStringIndexmapkey := iNdEx + intStringLenmapkey
			if postStringIndexmapkey > l {
				return io.ErrUnexpectedEOF
			}
			mapkey := string(dAtA[iNdEx:postStringIndexmapkey])
			iNdEx = postStringIndexmapkey
			if m.DestConfigurations == nil {
				m.DestConfigurations = make(map[string]*DestinationConfig)
			}
			if iNdEx < postIndex {
				var valuekey uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCounselor
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					valuekey |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				var mapmsglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCounselor
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					mapmsglen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if mapmsglen < 0 {
					return ErrInvalidLengthCounselor
				}
				postmsgIndex := iNdEx + mapmsglen
				if mapmsglen < 0 {
					return ErrInvalidLengthCounselor
				}
				if postmsgIndex > l {
					return io.ErrUnexpectedEOF
				}
				mapvalue := &DestinationConfig{}
				if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
					return err
				}
				iNdEx = postmsgIndex
				m.DestConfigurations[mapkey] = mapvalue
			} else {
				var mapvalue *DestinationConfig
				m.DestConfigurations[mapkey] = mapvalue
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCounselor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCounselor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DestinationConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCounselor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DestinationConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DestinationConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Command", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Command = append(m.Command, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = append(m.Args, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Env", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Env = append(m.Env, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Conf", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var keykey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				keykey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapkey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLenmapkey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapkey := int(stringLenmapkey)
			if intStringLenmapkey < 0 {
				return ErrInvalidLengthCounselor
			}
			postStringIndexmapkey := iNdEx + intStringLenmapkey
			if postStringIndexmapkey > l {
				return io.ErrUnexpectedEOF
			}
			mapkey := string(dAtA[iNdEx:postStringIndexmapkey])
			iNdEx = postStringIndexmapkey
			if m.Conf == nil {
				m.Conf = make(map[string]string)
			}
			if iNdEx < postIndex {
				var valuekey uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCounselor
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					valuekey |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				var stringLenmapvalue uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCounselor
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLenmapvalue |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLenmapvalue := int(stringLenmapvalue)
				if intStringLenmapvalue < 0 {
					return ErrInvalidLengthCounselor
				}
				postStringIndexmapvalue := iNdEx + intStringLenmapvalue
				if postStringIndexmapvalue > l {
					return io.ErrUnexpectedEOF
				}
				mapvalue := string(dAtA[iNdEx:postStringIndexmapvalue])
				iNdEx = postStringIndexmapvalue
				m.Conf[mapkey] = mapvalue
			} else {
				var mapvalue string
				m.Conf[mapkey] = mapvalue
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkDir", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkDir = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Periodic", wireType)
			}
			m.Periodic = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Periodic |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCounselor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCounselor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCounselor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCounselor(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCounselor
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCounselor
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthCounselor
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowCounselor
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipCounselor(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthCounselor = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCounselor   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("pb/counselor.proto", fileDescriptorCounselor) }

var fileDescriptorCounselor = []byte{
	// 576 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0x9c, 0xa4, 0x3f, 0xbe, 0x69, 0xf5, 0x85, 0x0b, 0xa5, 0xd3, 0x50, 0xd2, 0x28, 0x6c,
	0x42, 0x11, 0xb1, 0x68, 0x91, 0x40, 0xdd, 0x81, 0xc3, 0x12, 0x09, 0x19, 0xb1, 0xa9, 0x10, 0xd1,
	0xc4, 0xbe, 0x4d, 0xad, 0xc6, 0x9e, 0x61, 0x66, 0x1a, 0x54, 0x21, 0x36, 0xbc, 0x02, 0x1b, 0x58,
	0xf3, 0x32, 0x2c, 0x91, 0x78, 0x01, 0x54, 0x78, 0x06, 0xd6, 0x68, 0xc6, 0x34, 0xb4, 0x24, 0xd9,
	0x44, 0x62, 0xc3, 0x6e, 0xee, 0xb9, 0xc7, 0xe7, 0xdc, 0x3f, 0x19, 0x50, 0xf6, 0x83, 0x58, 0x1c,
	0xe7, 0x9a, 0x86, 0x42, 0x75, 0xa4, 0x12, 0x46, 0x60, 0x49, 0xf6, 0xeb, 0x9b, 0x03, 0x21, 0x06,
	0x43, 0x0a, 0xb8, 0x4c, 0x03, 0x9e, 0xe7, 0xc2, 0x70, 0x93, 0x8a, 0x5c, 0x17, 0x8c, 0xd6, 0x8f,
	0x0a, 0x60, 0x78, 0x48, 0xf1, 0xd1, 0x83, 0xd8, 0xc2, 0x11, 0xbd, 0x8c, 0x48, 0x4b, 0x44, 0xa8,
	0xe4, 0x3c, 0x23, 0xe6, 0x35, 0xbd, 0xb6, 0x1f, 0xb9, 0x37, 0x32, 0x58, 0x8a, 0x45, 0x96, 0xf1,
	0x3c, 0x61, 0xa5, 0x66, 0xb9, 0xed, 0x47, 0x67, 0xa1, 0x65, 0x73, 0x35, 0xd0, 0xac, 0xec, 0x60,
	0xf7, 0xc6, 0x1a, 0x94, 0x29, 0x1f, 0xb1, 0x8a, 0x83, 0xec, 0x13, 0xef, 0x42, 0x25, 0x16, 0xf9,
	0x01, 0x5b, 0x68, 0x96, 0xdb, 0xd5, 0x9d, 0x66, 0x47, 0xf6, 0x3b, 0x93, 0xce, 0x9d, 0x50, 0xe4,
	0x07, 0x8f, 0x72, 0xa3, 0x4e, 0x22, 0xc7, 0xc6, 0x0d, 0x58, 0x7e, 0x25, 0xd4, 0x51, 0x2f, 0x49,
	0x15, 0x5b, 0x74, 0xd5, 0x2c, 0xd9, 0xb8, 0x9b, 0x2a, 0xac, 0xc3, 0xb2, 0x24, 0x95, 0x8a, 0x24,
	0x8d, 0xd9, 0x52, 0xd3, 0x6b, 0x2f, 0x44, 0xe3, 0x18, 0xaf, 0x03, 0x68, 0xc3, 0x0d, 0xf5, 0x62,
	0x91, 0x10, 0x5b, 0x76, 0x1f, 0xfa, 0x0e, 0x09, 0x45, 0x42, 0x78, 0x03, 0x56, 0x8b, 0x74, 0x46,
	0x5a, 0xf3, 0x01, 0x31, 0xdf, 0x31, 0x56, 0x1c, 0xf8, 0xb8, 0xc0, 0x70, 0x13, 0x7c, 0x93, 0x66,
	0xa4, 0x0d, 0xcf, 0x24, 0x83, 0x42, 0x62, 0x0c, 0xe0, 0x4d, 0xa8, 0x25, 0xa4, 0x4d, 0x9a, 0xbb,
	0x79, 0xf6, 0x24, 0x37, 0x87, 0xac, 0xea, 0x48, 0xff, 0x9f, 0xc3, 0x9f, 0x70, 0x73, 0x68, 0x0b,
	0xd5, 0x34, 0xa4, 0xd8, 0x08, 0xc5, 0x56, 0x1c, 0x65, 0x1c, 0x63, 0x0f, 0x2e, 0x5b, 0x7a, 0xcf,
	0x36, 0x9b, 0x0e, 0x8e, 0x55, 0xb1, 0x1d, 0xb6, 0xea, 0x86, 0xd4, 0x99, 0x31, 0xa4, 0x2e, 0x69,
	0x13, 0x5e, 0xf8, 0xa0, 0x18, 0x19, 0x26, 0x13, 0x89, 0xfa, 0x3d, 0xf0, 0xc7, 0x33, 0xb5, 0x5b,
	0x39, 0xa2, 0x93, 0x5f, 0x6b, 0xb5, 0x4f, 0xbc, 0x02, 0x0b, 0x23, 0x3e, 0x3c, 0x26, 0x56, 0x72,
	0x58, 0x11, 0xec, 0x95, 0xee, 0x7b, 0xf5, 0xe7, 0xb0, 0x3e, 0xc3, 0x67, 0x8a, 0xcc, 0xad, 0xf3,
	0x32, 0xd5, 0x9d, 0x35, 0x5b, 0x78, 0xf7, 0xf7, 0x18, 0x0a, 0x91, 0x73, 0xea, 0xad, 0x0f, 0x65,
	0xb8, 0x34, 0x41, 0xf8, 0x2b, 0x77, 0xb7, 0x7b, 0xe1, 0xee, 0xb6, 0xa6, 0x56, 0xf6, 0x2f, 0x9e,
	0xdd, 0xdc, 0x9b, 0xdf, 0xf9, 0x58, 0x86, 0x5a, 0x78, 0xf6, 0x2b, 0x79, 0x4a, 0x6a, 0x94, 0xc6,
	0x84, 0xfb, 0x50, 0x0d, 0x15, 0xd9, 0x4e, 0xec, 0x3d, 0xe2, 0xd5, 0xe9, 0xa7, 0x59, 0x9f, 0x81,
	0xb7, 0xae, 0xbd, 0xfd, 0xf2, 0xfd, 0x5d, 0x69, 0xad, 0x55, 0x0b, 0x46, 0x77, 0x82, 0xd8, 0xe6,
	0xb9, 0xcb, 0xeb, 0x3d, 0x6f, 0x1b, 0x25, 0xf8, 0x11, 0x71, 0x39, 0x9f, 0xf2, 0xae, 0x53, 0xbe,
	0x8d, 0xeb, 0x7f, 0x2a, 0x07, 0xaf, 0xed, 0xfd, 0xbc, 0xd9, 0x47, 0x9c, 0x30, 0x45, 0x0e, 0xd5,
	0x67, 0x32, 0x99, 0xbb, 0x9b, 0x96, 0xf3, 0xdc, 0xac, 0xcf, 0xf2, 0xb4, 0x4d, 0xbd, 0x80, 0x6a,
	0x97, 0x86, 0x34, 0xaf, 0xc5, 0x96, 0xb3, 0xd8, 0xd8, 0x9e, 0x65, 0xf1, 0xb0, 0xf6, 0xe9, 0xb4,
	0xe1, 0x7d, 0x3e, 0x6d, 0x78, 0x5f, 0x4f, 0x1b, 0xde, 0xfb, 0x6f, 0x8d, 0xff, 0xfa, 0x8b, 0xee,
	0x9f, 0xbe, 0xfb, 0x33, 0x00, 0x00, 0xff, 0xff, 0x48, 0xf9, 0x01, 0x10, 0x0b, 0x06, 0x00, 0x00,
}
